### ISSUE TITLE
Mutex in different isolates

### ISSUE THREAD

**Issue by DasElias** [hoylen/dart-mutex#9]
Is it possible to share a `Mutex` through different isolates?

**Comment by hoylen** [comment]
No. Not directly, since a mutex object is state that is stored in memory.

From the [concurrency guide](https://dart.dev/guides/language/concurrency#how-isolates-work), _"Each isolate has its own memory heap, ensuring that none of the state in an isolate is accessible from any other isolate. Because there’s no shared memory, you don’t have to worry about mutexes or locks."_

A possible solution is to have only one mutex instantiated in an isolate (possibly the main isolate), and the other isolates interacts with that isolate via messages. That is, "sharing the mutex" by actually "sharing the isolate it is in".
